// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import LoadingOverlay from "@/components/layout/LoadingOverlay";
import { LoadingOverlayProvider } from "@/context/LoadingOverlayContext";
import AppWrapper from "@/components/layout/AppWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoadingOverlayProvider>
          <AppWrapper>{children}<LoadingOverlay text="Chargement..." />
</AppWrapper>
        </LoadingOverlayProvider>
      </body>
    </html>
  );
}
